logging:  level:    '[com.springboot.demo.apigateway]': DEBUG
    
      

server:
  port: 9191
  
  
  
spring:  zipkin:    base-url: http://localhost:9411/
  main:    web-application-type: reactive
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      discovery:        locator:          enabled: true
          lower-case-service-id: true
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
         # filters:
          #  - name: CircuitBreaker
         #     args:
            #    name: USER-SERVICE
            #    fallbackuri: forward:/userServiceFallback
        - id: DEPARTMENT-SERVICE
          uri: lb://DEPARTMENT-SERVICE
          predicates:
            - Path=/departments/**
          filters:
         #   - name: CircuitBreaker
          #    args:
           #     name: DEPARTMENT-SERVICE
             #   fallbackuri: forward:/departmentServiceFallback  sleuth:    reactor:      instrumentation-type: decorate-on-each 
     
    

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
  
      
      