server:
  port: 9295
  
spring:
  application:
    name: CONFIG-SERVER

  cloud:
    config:
      server:
        git:
          uri: https://github.com/Pallava/configServer
          default-label: main
          clone-on-start: true  
            
