logging:
  level:
    org:
      springframework: DEBUG
server:
  port: 9191
  
  
  
spring:
  main:    web-application-type: reactive
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
         # filters:
          #  - name: CircuitBreaker
         #     args:
            #    name: USER-SERVICE
            #    fallbackuri: forward:/userServiceFallback
        - id: DEPARTMENT-SERVICE
          uri: lb://DEPARTMENT-SERVICE
          predicates:
            - Path=/departments/**
          filters:
         #   - name: CircuitBreaker
          #    args:
           #     name: DEPARTMENT-SERVICE
             #   fallbackuri: forward:/departmentServiceFallback

    

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
  

      
      